### ISSUE TITLE
Update to FDC3 2.1

### ISSUE THREAD

**Issue by bingenito** [finos/fdc3-dotnet#74]
Checklist extracted from FDC3 CHANGELOG

[Added](https://github.com/finos/FDC3/blob/master/CHANGELOG.md#added-1)

- ~~[ ] Added CreateInteraction intent. To be used when a user wants to record an interaction into a system. New context Interaction also introduced. An interaction might be a call, IM, email, a meeting (physical or virtual) or the preparation of some specialist data. (https://github.com/finos/FDC3/pull/747)~~
- [x] Added TransactionResult context. A context type representing the result of a transaction initiated via FDC3. Its purpose is to provide a status and message (where needed) for the transaction and MAY wrap a returned context object. ([https://github.com/finos/FDC3/pull/761] (#761))
- [x] Added a MalformedContext error to the OpenError, ChannelError and ResolveError enumerations, to be used when broadcast, open, findIntents, raiseIntents, and other related functions are passed an invalid context Object. (https://github.com/finos/FDC3/pull/972)
- ~~[ ] Added error examples to the /v2 App Directory API routes (https://github.com/finos/FDC3/pull/973)~~
- ~~[ ] Added a SendChatMessage intent to be used when a user wants to send a message to an existing chat room. (https://github.com/finos/FDC3/pull/794)~~
- [x] Added a context type representing a chat message (fdc3.chat.message). (https://github.com/finos/FDC3/pull/794)
- [x] Added a context type representing a chat room (fdc3.chat.room). (https://github.com/finos/FDC3/pull/794)
- [x] Added a chat Message type in order to describe messages with rich content and attachments. (https://github.com/finos/FDC3/pull/779)
- [x] Added an Action type, encapsulating either a Context or the association of a Context with an Intent inside another object. (https://github.com/finos/FDC3/pull/779)
- ~~[ ] Added a ViewChat Intent to be used when a user wants to open an existing chat room. (https://github.com/finos/FDC3/pull/796)~~
- ~~[ ] Added a ViewMessages intent to be used when a user wants to search and see a list of messages. (https://github.com/finos/FDC3/pull/797)~~
- [x] Added a context type representing a ChatSearchCriteria (fdc3.chat.searchCriteria). (https://github.com/finos/FDC3/pull/797)
- ~~[ ] Added an indication that applications, that can be launched to receive intents or context via a raised intent or open with context, SHOULD add their context or intent listeners via the API within 15 seconds, and that Desktop Agents MUST allow at least a 15 second timeout for them to do so, and MAY set a longer timeout (https://github.com/finos/FDC3/pull/987)~~
- [ ] ~~Added [@experimental](https://fdc3.finos.org/docs/fdc3-compliance#experimental-features) Order, OrderList, Product, Trade & TradeList context types.~~(https://github.com/finos/FDC3/pull/1021)
- ~~[ ] Added Agent Bridging as an [@experimental](https://fdc3.finos.org/docs/fdc3-compliance#experimental-features) 5th part of the FDC3 Standard. (https://github.com/finos/FDC3/pull/968)~~
- ~~[ ] Added a description of the standards use of JSON Schema to define context types and Bridging messages. (https://github.com/finos/FDC3/pull/1020)~~
- ~~[ ] Documentation for standardized Context types was added to their JSON Schema files and TypeScript interfaces generated from them, so that they may act as a 'single source of truth' for Context definitions. (https://github.com/finos/FDC3/pull/1020)~~

[Changed](https://github.com/finos/FDC3/blob/master/CHANGELOG.md#changed-1)

- [x] Updated definition of the ChatInitSettings context type to use the new Message type. (https://github.com/finos/FDC3/pull/779)
- ~~[ ] Updated the StartChat intent to return a reference to the room. (https://github.com/finos/FDC3/pull/794)~~
- [x] Updated definition of the Instrument context type to include optional market identifiers (https://github.com/finos/FDC3/pull/819)
- ~~[ ] Corrected API functions and object types to always use string instead of String (https://github.com/finos/FDC3/pull/924)~~
- [x] Updated definition of the otherConfig element of the Chart context type from an Object to an array of Contexts as this allows the type of each additional item of config to be examined before it is used (https://github.com/finos/FDC3/pull/985)
- [x] Corrected the appD interop.appChannels metadata to use an id field to identify channels, rather than name (https://github.com/finos/FDC3/pull/981)
- ~~[ ] The App Directory OpenAPI schema was converted from YAML to JSON Schema, containing the same definitions. (https://github.com/finos/FDC3/pull/1035)~~
- ~~[ ] Switched to union types (from enums) for constrained string values in generated source files as they provide better type checking and cross-compatability of types. (https://github.com/finos/FDC3/pull/1093)~~

[Deprecated](https://github.com/finos/FDC3/blob/master/CHANGELOG.md#deprecated-1)

- [x] Deprecated the name field in AppD records, to match the deprecation of API signatures and metadata objects using name (see https://github.com/finos/FDC3/pull/722) in 2.0. (https://github.com/finos/FDC3/pull/928)
- [x] Deprecated IntentMetadata.displayName and the appD record's interop.intents.listensFor[].displayName field in favor of using intent names for display (which are required to be recognizable) as it can be set differently for each application in the appD (https://github.com/finos/FDC3/pull/926)
- [x] Deprecated the customConfig field in an AppD record due to the lack of a standard API to retrieve it. To be replaced with an applicationConfig element with a Desktop Agent API call to retrieve it in a future version (see https://github.com/finos/FDC3/issues/1006 for more details). Also deprecates the customCOnfig element of an Intent configuration due to a lack of documented use cases. (https://github.com/finos/FDC3/pull/982)

[Fixed](https://github.com/finos/FDC3/blob/master/CHANGELOG.md#fixed-1)

- [x] Corrected chatInitSettings context schema to incorporate the Context schema. (https://github.com/finos/FDC3/pull/869)
- [x] Corrected schema syntax in chatInitSettings and renamed the public property to isPublic (as public is a reserved keyword in javascript). (https://github.com/finos/FDC3/pull/875)
- ~~[ ] Further clarified the difference between the behavior of User channels and other channel types on joinUserChannel/addContextListener. (https://github.com/finos/FDC3/pull/971)~~
- ~~[ ] Clarified description of the behavior of IntentResolution.getResult() when the intent handler returned void (which is not an error). (https://github.com/finos/FDC3/pull/1004)~~
- ~~[ ] An error was fixed in the appD schema where launch details sub-schemas were combined with oneOf, rather than anyOf. This causes validation errors for web or online native apps as their details elements overlap on a url field. (https://github.com/finos/FDC3/pull/1034)~~
- ~~[ ] The appD icon and screenshot sub-schemas were updated to require the src value is set and restrict additional values, ensuring that common mistakes (such as ussing a url rather than src field are caught by the schemas when used to validate. (https://github.com/finos/FDC3/pull/1037)~~
- ~~[ ] Linting, spell checking other corrections were applied to markdown syntax throughout the FDC3 documentation (https://github.com/finos/FDC3/pull/1032)~~
- ~~[ ] Corrected bad example URLs in the App Directory overview/discovery page in the current and past versions as they did not agree with the paths provided in the API specification and OpenAPI schema. (https://github.com/finos/FDC3/pull/1060)~~
- [x] Correct inconsistent casing of fdc3.timeRange (https://github.com/finos/FDC3/pull/1240)

**Comment by bingenito** [comment]
Work will start now that 2.0 has been transferred and republished

**Comment by bingenito** [comment]
Experimental Order, OrderList, Product, Trade & TradeList context types will be intentionally left out until official (unless requested)

**Comment by bingenito** [comment]
Intents are still not defined/listed within fdc3-dotnet so any additions to enums/constants are not replicated

**Comment by kriswest** [comment]
> Intents are still not defined/listed within fdc3-dotnet so any additions to enums/constants are not replicated

@bingenito This is all we have in TS for intents: https://github.com/finos/FDC3/blob/fdc3-for-web/src/intents/Intents.ts
Theres this JSON file as well (which contains displayNames that should go as they are deprecated). Perhaps you could script something based on the file?

I note the following are missing from the JSON file: SendChatMessage, ViewAnalysis, ViewChat, ViewMessages - I'll drop a quick PR to fix those ommissions

**Comment by kriswest** [comment]
> Experimental Order, OrderList, Product, Trade & TradeList context types will be intentionally left out until official (unless requested)

Boo, here I was hoping you'd be helping to drive getting them right :-p

**Comment by bingenito** [comment]
> > Intents are still not defined/listed within fdc3-dotnet so any additions to enums/constants are not replicated
> 
> @bingenito This is all we have in TS for intents: https://github.com/finos/FDC3/blob/fdc3-for-web/src/intents/Intents.ts Theres this JSON file as well (which contains displayNames that should go as they are deprecated). Perhaps you could script something based on the file?
> 
> I note the following are missing from the JSON file: SendChatMessage, ViewAnalysis, ViewChat, ViewMessages - I'll drop a quick PR to fix those ommissions

@kriswest As this was never there for unpublished 1.2 or 2.0, I'll leave out of this PR but will create a separate issue to add an Intents.cs with public static strings.

**Comment by kriswest** [comment]
Added a PR to fix and simplify the JSON file: https://github.com/finos/FDC3/pull/1304
